### ISSUE TITLE
Params and Body

### ISSUE THREAD

**Issue by hmajid2301** [wI2L/fizz#42]
Is it possible to have parameters and the body passed to a function? 

For example let's say my endpoint is POST `/game/{name}/question`.

Where the defintion looks like:

```go
fizzApp.Group("/game", "game", "Related to managing the game types.")
// ...

func route(grp *fizz.RouterGroup) {
        / ...
	grp.POST("/:name/question", []fizz.OperationOption{
		fizz.Summary("Add a new question to a game type."),
	}, tonic.Handler(controllers.AddQuestion, http.StatusOK))
}
```

and the function definition looks something like:

```go
func AddQuestion(_ *gin.Context, params *models.GameParams, question *models.NewQuestion) (struct{}, error)
```

However I get the following error message:

```go
 incorrect number of input parameters for handler ontrollers.AddQuestion expected 1 or 2, got 3
```

Is there another way to get the body and the parameters passed to a function ? 
Thanks

**Comment by wI2L** [comment]
Hello.

This is not related to this library, but to loopfz/tonic, which define the `tonic.Handler` type. See https://github.com/loopfz/gadgeto/tree/master/tonic for reference.

What you should do is relying on a single type for your input parameter in the handler. You may use embedded structs in this case, to split common field in their own struct type.

**Comment by hmajid2301** [comment]
I'm pretty new to golang would you mind showing me an example ?

**Comment by wI2L** [comment]
Sure.
So, according yo what you said, your route `game/:name/question` should be represented with an input type like the following, to use in the handler's definition. This type defines the parameters of the body, but it also "embed" the game parameters through the type `GameParams`.
```go
type NewQuestionIn struct {
    GameParams
    Field1 string `json:"field1"`
    Field2 string `json:"field2"`
}

type GameParams struct {
    Name string `path:"name"`
    APIKey string `header:"X-Api-Key"` // for example, if you need to bind headers
}
```

The handler should then have the following prototype:
```go
func AddQuestion(c *gin.Context, in *NewQuestionIn) ("return type", error)
```

I imagine that you may have a`Question` model type, like so:
```go
type Question struct {
    ...
}
```
If so, you may reuse it. Embed it in the input type used in the handler:
```go
type NewQuestionIn struct {
    GameParams
    Question
}
```
And the handler becomes:
```go
func AddQuestion(c *gin.Context, in *NewQuestionIn) (*Question, error)
```
Here i assume that the handler should return a `Question` object since that's the behavior of CREATE methods in traditional CRUD APIs.

**Comment by wI2L** [comment]
I suggest that you take a look at the [example](https://github.com/wI2L/fizz/tree/master/examples/market). It doesn't show [types composition](https://golangbot.com/inheritance/), but it's a good start.
